http:
  path: localhost
  port: 8000
database:
  driver: mysql
  source: dev:dev@tcp(localhost:3306)/db_backend
redis:
  network: tcp
  address: 127.0.0.1:6379
  username: dev
  password: dev
jwt:
  secret: abcdefgh
  issuer: api
  expired: 24
